### ISSUE TITLE
Clean up the scaling numbers

### ISSUE THREAD

**Issue by dydx-git** [dydx-git/virtual-dressing-mirror#2]
@nawalmunif Please round or truncate the floating points in the models.js file

**Comment by abdul99ahad** [comment]
What's the use of those offsets?

**Comment by dydx-git** [comment]
I'm a bit confused too. @nawalmunif Please elaborate

**Comment by nawalmunif** [comment]
Previously all models were loading directly on face. So the offsets were specifying the position where the models should be loaded, as in on the body.

**Comment by abdul99ahad** [comment]
@nawalmunif yes you're right, that was my mistake I was aligning models w.r.t nose but now we've rectified it and we're aligning w.r.t hips so I think these offsets won't be of any help now. 
@dydx-git Remarks?

**Comment by nawalmunif** [comment]
@abdul99ahad models still loading on face

**Comment by abdul99ahad** [comment]
Do whatever you think is right.

**Comment by dydx-git** [comment]
> @nawalmunif yes you're right, that was my mistake I was aligning models w.r.t nose but now we've rectified it and we're aligning w.r.t hips so I think these offsets won't be of any help now.
> @dydx-git Remarks?

I have no idea. @nawalmunif does messing with the offset help in any way?

**Comment by nawalmunif** [comment]
I checked previous commits. 420 is added in yOffset. I don’t know what purpose it is serving but if we are adding 420, model lands on the body. @abdul99ahad since it was committed by you so ….

**Comment by abdul99ahad** [comment]
At the end of the day, we don't want to land model on blazepose coordinates but on mirror's reflection so it doesn't matter anyway. Leave this and delete the offsets.

**Comment by dydx-git** [comment]
Okay
