### ISSUE TITLE
Merge this repo with UI

### ISSUE THREAD

**Issue by dydx-git** [dydx-git/virtual-dressing-mirror#4]
@Usmaneeyy  Please merge the latest commit from the main branch to latest in PandemUI

**Comment by Usmaneeyy** [comment]
PandemUI has been merged with latest commit of the main branch and now the Final UI resides in the PandemUI branch.
Closing issue

**Comment by dydx-git** [comment]
Okay, did you attach the hand tracker for navigation?

**Comment by Usmaneeyy** [comment]
No i didn't, it wasn't in the latest commit and the issue was to merge the UIs.

**Comment by dydx-git** [comment]
No, the issue was to merge this repo and all its functionality with the UI. Hand tracker is definitely in the latest repo. It's commented out as getDirection. Please fix

**Comment by Usmaneeyy** [comment]
Okay i'll check it then, didn't know about that
